name: CI Placeholder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Add your build/test steps here
      - name: Placeholder
        run: echo "Add CI steps here"
