name: Link Checker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly on Sundays at midnight UTC
    - cron: '0 0 * * 0'

jobs:
  link-check:
    runs-on: ubuntu-24.04
    name: Check links in markdown files
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.9.1
      with:
        args: --verbose --no-progress --exclude-mail './**/*.md'
        fail: true
        format: markdown
        output: ./lychee-report.md
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: Comment PR with link check results
      if: failure() && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          if (fs.existsSync('./lychee-report.md')) {
            const report = fs.readFileSync('./lychee-report.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## Link Check Results\n\n' + report
            });
          }