name: Markdown CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  markdown-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install markdownlint-cli and markdown-link-check
        run: |
          npm install -g markdownlint-cli markdown-link-check
      - name: Run markdownlint
        run: |
          markdownlint '**/*.md'
      - name: Check Markdown links
        run: |
          find . -name '*.md' -print0 | xargs -0 -n1 markdown-link-check -q
